### ISSUE TITLE
Put link to Google Group in more prominent location

### ISSUE THREAD

**Issue by danmohad** [MaCFP/macfp-db#474]
If the Google Group is indeed a sanctioned forum for MaCFP discussions, I suggest putting a link to that group in a more prominent location in this repo, such as [the readme](https://github.com/MaCFP/macfp-db#readme). I only found out about the group today. Right now, the link only exists in the Latex code for the [Guidelines for Participation](https://github.com/MaCFP/macfp-db/blob/72567347ce1818e8b7c6cc8f38e4d7d702ba9c76/Documents/MaCFP-3/Guidelines_for_Participation_MaCFP3.tex#L608).

**Comment by rmcdermo** [comment]
Hi Danyal,

Google Group is deprecated.  We will be officially migrating to GitHub
Discussions after MaCFP-3.   For now, discussions that started on Google
are continuing.

Best,
Randy

**Comment by danmohad** [comment]
Ah, ok. Understood, thank you!

Best,
Danyal

**Comment by danmohad** [comment]
Ah, ok. Understood, thank you!

Best,
Danyal
